import { useEffect, useRef, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { ArrowDown, ArrowUp, ArrowUpRight, ArrowRight, Download, Menu, X, Plus, Minus, BriefcaseBusiness } from 'lucide-react';
import { portfolio as p } from './content';
import type { Credential, Project } from './content';

function Label({children, light=false}: {children:ReactNode;light?:boolean}) {return <div className={`eyebrow ${light?'light':''}`}><span/>{children}</div>}
function Photo({src,alt,className='',priority=false}: {src:string;alt:string;className?:string;priority?:boolean}) {return <img src={src} alt={alt} className={className} loading={priority?'eager':'lazy'} decoding="async" width="1200" height="900"/>}
function DocumentFrame({credential}: {credential:Credential}) {
  return <div className={`document-frame frame-${credential.crop}`}><div className={`document-window crop-${credential.crop}`}><Photo src={credential.image} alt={`${credential.name} — photograph of the original document`}/></div></div>
}
function Modal({title,children,onClose}: {title:string;children:ReactNode;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const node=dialog.current;const previous=document.activeElement as HTMLElement|null;node?.showModal();document.body.style.overflow='hidden';return()=>{node?.close();document.body.style.overflow='';previous?.focus()}},[]);
  return <dialog ref={dialog} className="modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}} aria-labelledby="modal-title"><div className="modal-top"><span className="micro">Portfolio / Details</span><button className="icon-button" onClick={onClose} aria-label="Close details"><X/></button></div><h2 id="modal-title">{title}</h2>{children}</dialog>
}
function Contact() {
  const [errors,setErrors]=useState<Record<string,string>>({});const [state,setState]=useState<'idle'|'ready'|'error'>('idle');const [draft,setDraft]=useState('');
  function submit(e:FormEvent<HTMLFormElement>) {e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get('name')||'').trim();const email=String(data.get('email')||'').trim();const subject=String(data.get('subject')||'').trim();const message=String(data.get('message')||'').trim();const next:Record<string,string>={};if(name.length<2)next.name='Please enter your name (at least 2 characters).';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))next.email='Please enter a valid email address.';if(subject.length<3)next.subject='Please add a subject (at least 3 characters).';if(message.length<10)next.message='Please write a message (at least 10 characters).';setErrors(next);if(Object.keys(next).length){setState('error');e.currentTarget.querySelector<HTMLInputElement>(`[name="${Object.keys(next)[0]}"]`)?.focus();return}const url=`mailto:${p.person.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(`From: ${name}\nReply email: ${email}\n\n${message}`)}`;setDraft(url);setState('ready');window.location.href=url}
  return <section id="contact" className="contact section-pad"><div className="contact-grid"><div><Label light>Start a conversation</Label><h2>Let’s make<br/>good work <em>happen.</em></h2><p>{p.contact.intro}</p><a className="email-link" href={`mailto:${p.person.email}`}>{p.person.email}<ArrowUpRight size={22}/></a><div className="phones">{p.person.phones.map(phone=><a key={phone} href={`tel:${phone}`}>{phone.replace('+234','+234 ')}</a>)}</div><div className="socials">{p.socials.map(s=><a key={s.label} href={s.url} target="_blank" rel="noopener noreferrer">{s.label}<ArrowUpRight size={14}/></a>)}</div></div><form onSubmit={submit} noValidate><div className="form-row">{(['name','email'] as const).map(field=><div className="field" key={field}><label htmlFor={field}>{field==='name'?'Your name':'Email address'}</label><input id={field} name={field} type={field==='email'?'email':'text'} autoComplete={field==='email'?'email':'name'} required maxLength={120} placeholder={field==='name'?'How should I address you?':'you@example.com'} aria-invalid={!!errors[field]} aria-describedby={errors[field]?`${field}-error`:undefined}/>{errors[field]&&<span className="field-error" id={`${field}-error`}>{errors[field]}</span>}</div>)}</div><div className="field"><label htmlFor="subject">Subject</label><input id="subject" name="subject" required maxLength={160} placeholder="An opportunity, a project, a conversation…" aria-invalid={!!errors.subject} aria-describedby={errors.subject?'subject-error':undefined}/>{errors.subject&&<span className="field-error" id="subject-error">{errors.subject}</span>}</div><div className="field"><label htmlFor="message">Your message</label><textarea id="message" name="message" rows={4} required maxLength={4000} placeholder="Tell me a little about what you have in mind." aria-invalid={!!errors.message} aria-describedby={errors.message?'message-error':undefined}/>{errors.message&&<span className="field-error" id="message-error">{errors.message}</span>}</div><button className="button cream" type="submit">Prepare email <ArrowUpRight size={18}/></button><p className="form-note">Opens your email app with a prepared message. Send it there to reach me.</p><div className="form-status" role="status" aria-live="polite">{state==='error'&&'Please check the highlighted fields.'}{state==='ready'&&<>Your email draft is ready. It has not been sent yet. <a href={draft}>Open the draft again</a>, or email me directly if no email app is configured.</>}</div></form></div></section>
}
export default function App() {
  const [menu,setMenu]=useState(false);const [project,setProject]=useState<Project|null>(null);const [credential,setCredential]=useState<Credential|null>(null);const [gallery,setGallery]=useState<(typeof p.gallery)[number]|null>(null);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
  useEffect(()=>{if(!menu)return;function close(e:KeyboardEvent){if(e.key==='Escape')setMenu(false)}document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[menu]);
  return <><a className="skip" href="#main">Skip to content</a><header className="header"><a className="wordmark" href="#home" aria-label="Oluwatobi Faith home">OF<span>Oluwatobi Faith<span className="wordmark-sub">MANAGEMENT & OPERATIONS</span></span></a><button className="menu-toggle icon-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav id="navigation" className={menu?'nav open':'nav'} aria-label="Main navigation">{p.navigation.map(item=><a key={item.href} href={item.href} onClick={()=>setMenu(false)}>{item.label}</a>)}<a className="nav-contact" href="#contact" onClick={()=>setMenu(false)}>Let’s connect <ArrowUpRight size={15}/></a></nav></header>
  <main id="main"><section className="hero" id="home"><div className="hero-content"><Label light>Management · Storekeeping · Operations</Label><h1>People first.<br/>Details <br/><em>matter.</em></h1><div className="hero-person"><span className="person-line"/><div><h2>{p.person.name}</h2><p>{p.person.title}</p></div></div><p className="hero-intro">{p.person.statement}</p><div className="hero-actions"><a className="button cream" href="#experience">Explore my experience <ArrowUpRight size={18}/></a><a className="text-link" href={p.person.resume} download>Download CV <Download size={16}/></a></div></div><div className="hero-art"><div className="portrait-frame"><Photo src={p.person.portrait} alt="AI-enhanced studio portrait of Ojo Oluwatobi Faith, based on his original CV photograph" priority/><span>OJO OLUWATOBI FAITH / A PERSONAL PORTRAIT</span></div><div className="hero-art-number">01 / A PRACTICAL MIND. A PERSONAL APPROACH.</div></div><div className="hero-bottom"><span>Management. Organisation. Everyday responsibility.</span><a href="#about">Discover the story <ArrowDown size={15}/></a></div></section>
  <div className="intro-strip"><span>MANAGEMENT</span><span className="strip-dot"/><span>STOREKEEPING</span><span className="strip-dot"/><span>OPERATIONS & COORDINATION</span><BriefcaseBusiness size={20}/></div>
  <section id="about" className="about section-pad"><div className="section-top"><Label>The person behind the practice</Label><span className="section-index">01 / ABOUT</span></div><div className="about-grid reveal"><div><h2>More than<br/>a <em>résumé.</em></h2><p className="large-copy">Good management lives in the details. The people, the records, and the everyday work that keeps things moving.</p><a className="under-link" href="#contact">Get in touch <ArrowUpRight size={17}/></a></div><div className="about-story">{p.about.map((text,i)=><p key={i}>{text}</p>)}<div className="signature">Oluwatobi Faith<span>PRACTICAL EXPERIENCE. A STEADY APPROACH.</span></div></div></div><div className="stats reveal">{p.statistics.map(s=><div key={s.value}><span className="stat-value">{s.value}<span className="stat-dot">.</span></span><h3>{s.label}</h3><p>{s.detail}</p></div>)}</div></section>
  <section id="expertise" className="expertise section-pad"><div className="section-top"><Label>What I bring to the table</Label><span className="section-index">02 / EXPERTISE</span></div><div className="section-heading"><h2>A grounded<br/>kind of <em>expertise.</em></h2><p>Built through practical responsibility.<br/>Applied with care, clarity and purpose.</p></div><div className="expertise-list">{p.expertise.map(item=><div className="expertise-item reveal" key={item.number}><span className="expertise-number">{item.number}</span><div><h3>{item.title}</h3><p>{item.description}</p></div><ul className="skill-list">{item.skills.map(s=><li key={s}>{s}</li>)}</ul></div>)}</div></section>
  <section id="experience" className="experience section-pad"><div className="section-top"><Label>The career journey</Label><span className="section-index">03 / EXPERIENCE</span></div><div className="experience-grid"><div className="experience-heading"><h2>Responsibility,<br/>in <em>practice.</em></h2><p>From stockkeeping and bar management to operations, supervision and institutional coordination.</p><a className="under-link" href={p.person.resume} download>Read the full CV <Download size={16}/></a></div><div className="timeline">{p.experiences.map(job=><article className="timeline-entry reveal" key={job.id}><div className="timeline-date"><span className={'timeline-dot'}/>{job.dates}</div><h3>{job.role}</h3><div className="job-company">{job.company}{job.location&&<span> / {job.location}</span>}</div><p>{job.summary}</p>{job.responsibilities.length>0&&<details open={job.id==='tobex'}><summary>Responsibilities <Plus className="details-plus" size={17}/><Minus className="details-minus" size={17}/></summary><ul>{job.responsibilities.map(r=><li key={r}>{r}</li>)}</ul></details>}<div className="job-skills">{job.skills.map(s=><span key={s}>{s}</span>)}</div></article>)}</div></div></section>
  <section id="credentials" className="credentials section-pad"><div className="section-top"><Label>The supporting record</Label><span className="section-index">04 / CREDENTIALS</span></div><div className="section-heading"><h2>Education.<br/>Service. <em>Commitment.</em></h2><p>A degree, a year of national service, and recognition for community contribution. Three chapters, documented.</p></div><div className="credential-list">{p.credentials.map((c,i)=><button className="credential reveal" key={c.id} onClick={()=>setCredential(c)} aria-label={`Inspect ${c.name}`}><div className="credential-display"><span className="credential-number">0{i+1}</span><DocumentFrame credential={c}/><span className="document-open">View document</span></div><div className="credential-info"><span className="micro">{c.date}</span><h3>{c.name}</h3><p>{c.issuer}</p></div></button>)}</div><p className="quiet-note">Photographs of the original documents. Select a frame to inspect the certificate or view the full photograph.</p></section>
  <section id="work" className="work section-pad"><div className="section-top"><Label light>A closer look at the practice</Label><span className="section-index">05 / SELECTED WORK</span></div><div className="section-heading"><h2>The work<br/>behind the <em>title.</em></h2><p>A closer look at management, stockkeeping and coordination.<br/>A view into the responsibilities behind the titles.</p></div><div className="projects">{p.projects.map((item,i)=><article className={`project project-${i+1} reveal`} key={item.id}><button className="project-visual" onClick={()=>setProject(item)} aria-label={`Read practice note: ${item.title}`}><Photo src={item.image} alt={item.alt}/><span className="project-image-label">ILLUSTRATIVE IMAGE</span><span className="project-open"><ArrowUpRight size={25}/></span></button><div className="project-text"><div className="project-meta"><span>0{i+1} / {item.category}</span><span>{item.period}</span></div><h3>{item.title}</h3><p>{item.summary}</p><button className="under-link" onClick={()=>setProject(item)}>Read practice note <ArrowUpRight size={17}/></button></div></article>)}</div><p className="evidence-note">Illustrative photographs accompany experience notes based on my CV and confirmed work history. No unverified performance figures are claimed.</p></section>
  <section id="education" className="education section-pad"><div className="section-top"><Label>Knowledge, put into practice</Label><span className="section-index">06 / EDUCATION</span></div>{p.education.map(e=><div className="education-grid reveal" key={e.institution}><button className="education-art document-button" onClick={()=>setCredential(p.credentials[0])} aria-label="View university degree"><DocumentFrame credential={p.credentials[0]}/><span className="photo-caption">University degree · View document</span></button><div><span className="education-year">Class of {e.graduation}</span><h2>A foundation<br/>to build <em>on.</em></h2><h3>{e.degree}<br/>in {e.field}</h3><p>{e.institution}</p><p className="degree-honours">{e.achievement}</p><div className="education-note">An academic foundation in agriculture, complemented by practical experience in management, stockkeeping and operations.</div></div></div>)}</section>
  {p.service.enabled&&<section id="service" className="service section-pad"><div><Label light>Service & community</Label><span className="service-year">2025 — 2026</span></div><div><h2>{p.service.title}</h2><p className="service-dates">{p.service.organisation} · {p.service.dates}</p><p>{p.service.description}</p><a className="under-link" href="#credentials">Explore service certificates</a></div></section>}
  <section id="milestones" className="milestones section-pad"><div className="section-top"><Label>Moments that shaped the journey</Label><span className="section-index">07 / MILESTONES</span></div><h2>Progress, <em>with purpose.</em></h2><div className="milestone-list">{p.milestones.map(m=><article className="milestone reveal" key={m.year}><span>{m.year}</span><h3>{m.title}</h3><p>{m.description}</p></article>)}</div></section>
  <section id="journey" className="journey section-pad"><div className="section-top"><Label>Beyond the job titles</Label><span className="section-index">08 / THE JOURNEY</span></div><div className="section-heading"><h2>The person<br/>behind the <em>work.</em></h2><p>A practical background. A broader professional outlook.<br/>An evolving space for photographs from my journey.</p></div><div className="gallery">{p.gallery.map((g,i)=><button key={g.src} className={`gallery-item gallery-${i} reveal`} onClick={()=>setGallery(g)} aria-label={`Enlarge ${g.label}: ${g.caption}`}><Photo src={g.src} alt={g.alt}/><div><span>0{i+1} / {g.label}</span><ArrowUpRight size={20}/></div><small>{g.caption}</small></button>)}</div></section>
  {p.testimonials.enabled&&<section className="testimonials section-pad"><Label>In their words</Label>{p.testimonials.items.map((t,i)=><figure key={i}><blockquote>{t.quote}</blockquote><figcaption>{t.name} · {t.role}{t.placeholder&&' · SAMPLE TESTIMONIAL — NOT AN ENDORSEMENT'}</figcaption></figure>)}</section>}
  <Contact/></main><footer><div className="footer-top"><a className="footer-monogram" href="#home">OF<span>{p.person.name}</span></a><div><a href="#about">About</a><a href="#experience">Experience</a><a href="#work">Work</a><a href="#contact">Contact</a></div><a href="#home" className="back-top">Back to top <ArrowUp size={16}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {p.person.name}</span><span>People. Details. Responsibility.</span></div></footer>
  {project&&<Modal title={project.title} onClose={()=>setProject(null)}><div className="modal-meta">{project.company} / {project.period}</div><Photo src={project.image} alt={project.alt} className="modal-image"/><p className="micro">ILLUSTRATIVE IMAGE · EXPERIENCE NOTE</p><div className="case-study">{([{label:'Overview',text:project.overview},{label:'The focus',text:project.problem},{label:'The approach',text:project.solution}] as const).map(item=><section key={item.label}><h3>{item.label}</h3><p>{item.text}</p></section>)}<section><h3>My responsibilities</h3><ul>{project.responsibilities.map(r=><li key={r}>{r}</li>)}</ul></section><section><h3>Skills applied</h3><p>{project.skills.join(' · ')}</p></section><section><h3>Results & evidence</h3><p>{project.results}</p></section><section><h3>Reflection & lessons</h3><p>{project.lessons}</p></section></div><a className="button forest" href="#contact" onClick={()=>setProject(null)}>Discuss my experience <ArrowRight size={17}/></a></Modal>}
  {credential&&<Modal title={credential.name} onClose={()=>setCredential(null)}><div className="credential-modal-frame"><DocumentFrame credential={credential}/></div><div className="modal-meta">{credential.issuer} / {credential.date}</div><p>{credential.description}</p><a href={credential.image} className="under-link" target="_blank" rel="noopener noreferrer">View full original photograph</a>{credential.credentialId&&<p>Credential ID: {credential.credentialId}</p>}{credential.verificationUrl&&<a href={credential.verificationUrl} className="under-link" target="_blank" rel="noopener noreferrer">Verify credential</a>}</Modal>}
  {gallery&&<Modal title={gallery.label} onClose={()=>setGallery(null)}><Photo src={gallery.src} alt={gallery.alt} className="gallery-preview"/><p>{gallery.caption}{gallery.placeholder&&' — this image is not a record of a personal event or workplace.'}</p></Modal>}
  <script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@type':'Person',name:p.person.name,jobTitle:p.person.title,email:p.person.email,url:'https://oluwatobi-faith-portfolio.astute-plum-5148.chatgpt.site',alumniOf:{'@type':'CollegeOrUniversity',name:'Federal University of Technology, Minna'},knowsAbout:['Management','Storekeeping','Operations','Record keeping','Project monitoring','Farm management'],...(p.socials.length?{sameAs:p.socials.map(s=>s.url)}:{})})}</script></>
}
