export type Project = {id:string;title:string;category:string;company:string;period:string;image:string;alt:string;summary:string;overview:string;problem:string;solution:string;responsibilities:string[];skills:string[];results:string;lessons:string;placeholder:boolean};
export type Credential = {id:string;name:string;issuer:string;date:string;image:string;credentialId?:string;verificationUrl?:string;placeholder:boolean;crop:'degree'|'nysc'|'road-safety';description:string};
 
export const portfolio = {
  person: {name:'Ojo Oluwatobi Faith',shortName:'Oluwatobi Faith',title:'Manager · Storekeeper · Operations Professional',email:'tobet4rate@gmail.com',phones:['+2348150411425','+2349026655823'],country:'Nigeria',location:null as string|null,portrait:'/images/profile/profile-studio.webp',portraitOriginal:'/images/profile/profile-main.jpg',resume:'/OJO_OLUWATOBI_FAITH_CV.pdf',statement:'Management experience. A practical understanding of stockkeeping. A steady approach to people, records and day-to-day operations.'},
  navigation:[{label:'About',href:'#about'},{label:'Expertise',href:'#expertise'},{label:'Experience',href:'#experience'},{label:'Credentials',href:'#credentials'},{label:'Journey',href:'#journey'}],
  socials:[] as {label:string;url:string}[],
  about:['My experience spans management, storekeeping and operational coordination. I have managed a farm, worked as a bar manager and gained stockkeeping experience at Olorumlami in Ogbomoso, Oyo State, in 2024.','At Big Tobex Farm Limited, my responsibilities included overseeing operations, maintaining records and supervising labour. My work at the National Centre for Agricultural Mechanization added experience in coordinating activities, following institutional protocols and preparing documentation.','Agriculture is an important part of my background, alongside livestock care at Judif Farm. Today, I bring that practical foundation to a wider professional direction: management, storekeeping and operations, with care for the people and details behind the work.'],
  statistics:[{value:'4',label:'Years in farm management',detail:'Big Tobex · 2021–2024'},{value:'2024',label:'Storekeeping experience',detail:'Olorumlami · Ogbomoso, Oyo State'},{value:'3',label:'Certificates on display',detail:'Degree · NYSC · Road safety service'}],
  expertise:[
    {number:'01',title:'Management & operations',description:'Experience overseeing daily operations, supervising people and maintaining the records that support organised work.',skills:['Operations management','Team supervision','Record keeping','Safety standards','Bar management']},
    {number:'02',title:'Storekeeping & organisation',description:'Stockkeeping experience at Olorumlami in Ogbomoso, complemented by a wider background in records and operational responsibility.',skills:['Stockkeeping','Storekeeping','Organisation','Attention to detail']},
    {number:'03',title:'Coordination & reporting',description:'Helping activities run with structure through monitoring, documentation and adherence to institutional processes.',skills:['Project monitoring','Visit coordination','Documentation','Reporting','Institutional protocols']},
    {number:'04',title:'Agriculture & animal care',description:'A specialist foundation in farm management and livestock care that adds depth to my operational experience.',skills:['Farm management','Crop production','Livestock care','Animal health programmes','Nutrition advice']}
  ],
  experiences:[
    {id:'olorumlami',dates:'2024',company:'Olorumlami',role:'Storekeeper',location:'Ogbomoso, Oyo State',summary:'Stockkeeping experience at Olorumlami, adding a storekeeping dimension to my management and operations background.',responsibilities:[],skills:['Stockkeeping','Storekeeping']},
    {id:'tobex',dates:'January 2021 — December 2024',company:'Big Tobex Farm Limited',role:'Farm Manager',location:null,summary:'Managed the daily operation of a farm, with responsibility for production, records, workforce supervision and safety.',responsibilities:['Oversaw crop production and livestock operations.','Maintained operational records.','Supervised labour for adherence to safety standards.','Diagnosed livestock ailments and supported productivity.'],skills:['Operations management','Record keeping','Team supervision']},
    {id:'officers',dates:'2022 — 2024',company:'Officers Mess',role:'Bar Manager',location:'Niger State',summary:'Management experience in a hospitality setting, alongside my wider operational career.',responsibilities:[],skills:['Management','Hospitality']},
    {id:'ncam',dates:'Dates not specified',company:'National Centre for Agricultural Mechanization (NCAM)',role:'Planning & Monitoring Officer',location:'Nigeria',summary:'Coordinated activities and documentation within an institution, supporting orderly visits and adherence to protocols.',responsibilities:['Coordinated and monitored official visits and activities within the centre.','Supported institutional protocols.','Prepared visitor documentation and reports.'],skills:['Coordination','Monitoring','Documentation']},
    {id:'judif',dates:'July 2025 — Present (per CV)',company:'Judif Farm',role:'Veterinary Officer',location:null,summary:'Practical animal health responsibilities within a working farm environment.',responsibilities:['Provide veterinary care, diagnose and treat livestock ailments.','Administer vaccinations and manage animal health programmes.','Advise on nutrition and breeding for livestock health.'],skills:['Livestock care','Animal health','Nutrition']}
  ],
  projects:[
    {id:'stockkeeping',title:'An organised approach to the everyday.',category:'Storekeeping',company:'Olorumlami · Ogbomoso, Oyo State',period:'2024',image:'/images/projects/project-03-cover.jpg',alt:'Illustrative pen and notebook; not a photograph of Olorumlami',summary:'Storekeeping experience that broadens a career in management and operations.',overview:'I worked in stockkeeping at Olorumlami in Ogbomoso, Oyo State, in 2024. This role and year were supplied directly for this portfolio.',problem:'This note introduces the stockkeeping role. Specific stock categories, systems and operational challenges have not yet been described.',solution:'The experience is presented as part of my wider management and operations background. Further detail can be added when confirmed.',responsibilities:['Stockkeeping at Olorumlami'],skills:['Stockkeeping','Storekeeping'],results:'No stock volumes, audit figures or quantified improvements are claimed.',lessons:'A detailed account of responsibilities and lessons can be added with supporting examples.',placeholder:false},
    {id:'operations',title:'People. Records. Responsibility.',category:'Management & operations',company:'Big Tobex Farm Limited',period:'2021 — 2024',image:'/images/projects/project-02-cover.jpg',alt:'Illustrative agricultural field; not a photograph of Big Tobex Farm',summary:'Four years of farm management, with responsibility for operations, records and workforce supervision.',overview:'A practice note based on my Farm Manager role at Big Tobex Farm Limited, as recorded in the CV.',problem:'The role brought production, livestock management, records and workforce safety together under daily operational responsibility.',solution:'Oversee operations, maintain records, supervise labour and support livestock health.',responsibilities:['Daily farm operations','Operational records','Workforce supervision and safety','Crop production and livestock management'],skills:['Management','Record keeping','Team supervision'],results:'The scope and dates of the role are documented. Quantitative performance figures have not been supplied.',lessons:'Approved examples of management decisions and outcomes can be added as a fuller case study.',placeholder:false},
    {id:'monitoring',title:'Keeping the details in order.',category:'Coordination & reporting',company:'NCAM, Nigeria',period:'Dates not specified',image:'/images/projects/project-03-cover.jpg',alt:'Illustrative writing workspace; not a photograph of NCAM',summary:'Coordination, institutional protocols and reporting behind the scenes.',overview:'A practice note covering my Planning & Monitoring Officer responsibilities at NCAM.',problem:'Official visits and activities required coordination, reliable documentation and adherence to protocols.',solution:'Coordinate and monitor visits, prepare visitor records and reports, and follow institutional processes.',responsibilities:['Official visit coordination','Activity monitoring','Visitor documentation and reporting'],skills:['Monitoring','Reporting','Coordination'],results:'No quantitative outcomes or confidential report samples are presented.',lessons:'This note can grow into a detailed project narrative when approved supporting material is available.',placeholder:false}
  ] satisfies Project[],
  education:[{institution:'Federal University of Technology, Minna',degree:'Bachelor of Agricultural Technology',field:'General Agriculture',graduation:'2024',achievement:'Second Class Honours (Lower Division)',image:'/images/certificates/degree-original.jpeg',alt:'Original university degree photograph supplied by Ojo Oluwatobi Faith'}],
  credentials:[
    {id:'degree',name:'Bachelor of Agricultural Technology',issuer:'Federal University of Technology, Minna',date:'28 February 2024',image:'/images/certificates/degree-original.jpeg',crop:'degree',placeholder:false,description:'General Agriculture · Second Class Honours (Lower Division). Qualification title transcribed from the supplied degree.'},
    {id:'nysc',name:'Certificate of National Service',issuer:'National Youth Service Corps',date:'29 July 2026',image:'/images/certificates/nysc-original.jpeg',crop:'nysc',placeholder:false,description:'One year of national service completed, from 30 July 2025 to 29 July 2026, as shown on the certificate.'},
    {id:'road-safety',name:'Road Safety CDS — Certificate of Service',issuer:'Federal Road Safety Corps CDS Group, Awka North LGA, Anambra State',date:'9 July 2026',image:'/images/certificates/road-safety-service-original.jpeg',crop:'road-safety',placeholder:false,description:'Recognition of diligent and selfless service under the FRSC Community Development Service group.'}
  ] as Credential[],
  milestones:[{year:'2021',title:'Stepping into management',description:'Began the Farm Manager role at Big Tobex Farm Limited.'},{year:'2024',title:'A broader practical foundation',description:'Completed my degree and gained storekeeping experience at Olorumlami in Ogbomoso.'},{year:'2026',title:'Service, completed',description:'Completed national service and received recognition from the Road Safety CDS group.'}],
  service:{enabled:true,title:'A year of service. A lasting perspective.',organisation:'National Youth Service Corps',dates:'30 July 2025 — 29 July 2026',description:'Completed one year of national service and received a Certificate of Service from the Federal Road Safety Corps CDS Group in Awka North, Anambra State. A chapter of community contribution alongside my professional journey.'},
  gallery:[{src:'/images/profile/profile-studio.webp',alt:'AI-enhanced studio portrait of Ojo Oluwatobi Faith, based on his original CV photograph',label:'The person',caption:'A refreshed portrait',placeholder:false},{src:'/images/projects/project-03-cover.jpg',alt:'Illustrative photograph of a pen and notebook',label:'The details',caption:'Illustrative workspace photograph',placeholder:true}],
  testimonials:{enabled:false,items:[{quote:'Replace this sample with an approved testimonial.',name:'Placeholder name',role:'Placeholder role',placeholder:true}]},
  contact:{heading:'Let’s make good work happen.',intro:'For opportunities in management, storekeeping, operations and coordination, I would be glad to hear from you.'}
};
